### ISSUE TITLE
Warning: Calling Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by rasmusbe** [tideways/homebrew-profiler#2]
``` bash
brew tap tideways/homebrew-profiler

==> Tapping tideways/profiler
Cloning into '/usr/local/Homebrew/Library/Taps/tideways/homebrew-profiler'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 19 (delta 4), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/tideways/homebrew-profiler/Formula/tideways-cli.rb:8:in `<class:TidewaysCli>'
Please report this to the tideways/profiler tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/tideways/homebrew-profiler/Formula/tideways-cli.rb:8:in `<class:TidewaysCli>'
Please report this to the tideways/profiler tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/tideways/homebrew-profiler/Formula/tideways-cli.rb:8:in `<class:TidewaysCli>'
Please report this to the tideways/profiler tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/tideways/homebrew-profiler/Formula/tideways-daemon.rb:8:in `<class:TidewaysDaemon>'
Please report this to the tideways/profiler tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/tideways/homebrew-profiler/Formula/tideways-daemon.rb:8:in `<class:TidewaysDaemon>'
Please report this to the tideways/profiler tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/tideways/homebrew-profiler/Formula/tideways-daemon.rb:8:in `<class:TidewaysDaemon>'
Please report this to the tideways/profiler tap!

Tapped 7 formulae (53 files, 98.7K)
```

``` bash
brew -v
Homebrew 1.0.8
Homebrew/homebrew-core (git revision 5fcbc; last commit 2016-10-25)
```

**Comment by yehosef** [comment]
Any update on when this can be merged/release?  thanks!
